### ISSUE TITLE
Call 1 prep

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/pathways-to-open-science#24]
- [x] add generic Zoom link to our Google Calendar invite (for the Pathways team) and our Seaside Chat doc; make sure all speakers know the link
  - note, @IleanaF might need to delete her Pathways calendar invites to team (and Barbara for Call 1) and create new invite with Zoom link and delete the Google Meet link. We've learned that some folks don't get updates in their calendar so they will only see the Google Meet link even after Zoom link is added. 
- [x] can I send reminder email from inside zoom to registrants? so they join via their registration link
- [x] get link to auto-join Openscapes Slack
- [x] day of Call 1, create "published" link for Call 1 Google Doc for (too many folks for simultaneous doc editing)
- [x] https://github.com/Openscapes/pathways-to-open-science/issues/23
- [x] ~create Debrief doc~ for post-Call team reflections - do this inside existing Seaside Chats doc; create heading for it including pre-Call activities like setting co-hosts

**Comment by IleanaF** [comment]
Hey @stefaniebutland 

I am sending the email to speakers to confirm their dates tomorrow, can the email/connect to speakers to know the link take place after 10:30 AM EST 1/18? or I can place it directly in the email as well! Is this correct?

 Join Zoom Meeting
[https://zoom.us/w/99820169140?tk=A1Jvu_Q_pygSjVDsFHX4gdCB_jgu_sIkAGdkhbuZJJk.DQYAAAAXPb7ntBZMdzJ3Mk02TlFPbVRrNHE2ZGZmMjdRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA](https://www.google.com/url?q=https://zoom.us/w/99820169140?tk%3DA1Jvu_Q_pygSjVDsFHX4gdCB_jgu_sIkAGdkhbuZJJk.DQYAAAAXPb7ntBZMdzJ3Mk02TlFPbVRrNHE2ZGZmMjdRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&sa=D&source=calendar&usd=2&usg=AOvVaw3Mji-yjx42x9-ceZdOQJSS)

Meeting ID: 998 2016 9140
One tap mobile

**Comment by stefaniebutland** [comment]
not that zoom link. That's a link unique to you from registration (I made that mistake in a community call and a bunch of ppl joined as Stef Butland and we didn't want to let them in 🤦🏼‍♀️ )

I'm looking for the general link and will DM you in Slack

**Comment by jules32** [comment]
hi @IleanaF @stefaniebutland FYI I was able to edit Ileana's message above and delete the zoom link so it doesn't cause confusion for anyone going forward :)

**Comment by stefaniebutland** [comment]
> can I send reminder email from inside zoom to registrants? so they join via their registration link

Yes. Reminder email can be sent from Zoom. Need to click each person > click re-send, but worth it cause it re-sends their individual link and details ([how-to](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0068036)). Stef will do this Tuesday Jan 23 morning.
Adding this to Approach Guide now

**Comment by stefaniebutland** [comment]
> add generic Zoom link to our Google Calendar invite (for the Pathways team)

Calendar invite is from Ileana. I added details to our Seaside Chats doc on how best for Ileana to do this. I added Zoom link to top of Seaside Chats doc and CommunityCallAgendas doc

**Comment by stefaniebutland** [comment]
>  get link to auto-join Openscapes Slack

@IleanaF Let me know what you think/decide about this. Typically, not many people from a cohort or event series become or stay active in Slack - that's totally normal. Some do. It doesn't cost us anything to offer access to this community.

I could create an invite link we can share with people during each session. That would get them in Slack. If you want to offer the private channel as well, I'll get notified when they join, and then I'd add them to private pathways channel (I'll know names from registrations)

**Comment by IleanaF** [comment]
Hi @stefaniebutland 

Just updated CC1 google calendar invitation and reshared without Google meet link, will be able to sit down and fix for remainder of calls on Thursday. 

Yes to Slack invitation. I love this line "It doesn't cost us anything to offer access to this community", agreed! 

So glad we can send a reminder! Awesome. 

Lastly, just sharing this note I got from Jason Williams - I have time to troubleshoot on Thursday but not beforehand so placing here in the meantime 

> On my calendar;
> 
> I went to the Zoom registration, but the dates stopped on Feb 15. Should I still use this link?

I saw on my calendar it had the zoom registration until the 22nd but I am missing the 29th. Wondering how it is popping up on others' calendars.

**Comment by stefaniebutland** [comment]
re: Zoom in calendars, that's odd and a little concerning. Mine from my registration show properly ending Feb 29 and with proper 1.5 and 1hr slots for CC's and coworking. 

> updated CC1 google calendar invitation and reshared without Google meet link

My updated invite still shows the Google Meet link (screenshot). When you have time, I'm happy to do a short cowork with you to go through the others if you like, with me as a 2nd pair of eyes.

<img width="439" alt="Screenshot 2024-01-22 at 2 41 39 PM" src="https://github.com/Openscapes/pathways-to-open-science/assets/11927811/ad9ddcd2-46e7-434d-b38c-7636950cf008">

**Comment by stefaniebutland** [comment]
Slack. Added this text to Agenda Resources section for all Community Calls and Coworking
> Continue our conversations by joining Openscapes Slack (_link to join is there_). We use Slack as a way to build community by hosting a space for people to connect with each other. We want it to be a supportive, trust-based community of folks doing (or learning to do!) data intensive science. Here’s[ some information](https://openscapes.github.io/approach-guide/approach/tooling.html#slack) to help you get comfortable whether you’re new to using Slack or you’re curious about how we use Slack for Openscapes. There is a private channel #pathways-to-opensci for participants in this series. We’ll invite you there after you’ve joined.
