### ISSUE TITLE
Call 1 followup

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/pathways-to-open-science#27]
- [x] save video to [pathways folder](https://drive.google.com/drive/folders/1UXMq1aJDXGk7yQILZbxLck3fEAGda3TJ?usp=drive_link)
- [x] website - link to video, slides
- [x] website - add resource links
- [x] website - update any speakers info
- [x] export registration list - save to planning folder
- [x] export Call 1 participants list - save to planning folder
- [x] Slack - add new joiners to private pathways channel; team member to post a welcome there

**Comment by stefaniebutland** [comment]
@IleanaF What affiliation info should I use for Bárbara Pinheiro? To parallel yours and Aliyah's

![Screenshot 2024-01-26 at 9 40 11 AM](https://github.com/Openscapes/pathways-to-open-science/assets/11927811/287fceb7-8023-46b2-9daa-188e731e4d4c)

**Comment by stefaniebutland** [comment]
https://openscapes.github.io/pathways-to-open-science/2024.html#call-1-january-25-what-is-open-science-anyway-what-can-it-mean-for-you

**Comment by IleanaF** [comment]
@stefaniebutland Reached out to Barbara to confirm. Will update here! Thank you so much. This looks great!

**Comment by IleanaF** [comment]
@stefaniebutland here is Bárbara's affiliation 

Here is my affiliation 
Dr. Barbara Pinheiro - Post Doc research fellow, [PELD CCAL- Universidade Federal de Alagoas, Maceió- Brazil ](https://sites.google.com/view/peld-costa-dos-corais-al/equipe?authuser=0)  * the link is for our page in Portuguese

Thank you!

**Comment by stefaniebutland** [comment]
added thank you!
