### ISSUE TITLE
Updates to Pathways website

### ISSUE THREAD

**Issue by IleanaF** [Openscapes/pathways-to-open-science#49]
- [x] Draft updated text for top of Pathways page

**Comment by jules32** [comment]
- [ ] Add LaWanda bio to Team

**Comment by stefaniebutland** [comment]
- [ ] First sentence for website; the sentence anyone will cp-paste to share:
https://openscapes.github.io/pathways-to-open-science/ 
Pathways to Open Science is a remote event series for Black environmental & marine researchers to build community for the future of data intensive science. This is an annual program next occurring in Jan through Feb 2025, registration opens soon at https://openscapes.github.io/pathways-to-open-science/. 

Use the prime real estate of the website for announcing coming back, move partners to a separate piece 

- [ ] HBCU logos added onto the website 
- [ ] Add NOAA fisheries as funder

**Comment by IleanaF** [comment]
**Edit to first sentence on website**

@stefaniebutland @jules32 what do you think of this wording? 

Pathways to Open Science is a remote event series for Black environmental & marine researchers to build community for the future of data intensive science. We empower our community by sharing our stories, learning together, and building skills to expand how data science can improve, accelerate, and support our science. The 2025 series will run weekly from January 23 through Feb 27, registration is now open!

 This text can be moved below and program details agter the current first paragraph 
> "This is an ongoing collaboration with Black in Marine Science ([BIMS](https://www.blackinmarinescience.org/)), Black Women in Ecology, Evolution, and Marine Science ([BWEEMS](https://www.bweems.org/)), and HBCU marine science professors. The program is led by Ileana Fenwick, with Alex Davis, PhD, and Aneese Williams. "

**Comment by jules32** [comment]
Yes I like this a lot Ileana!

**Comment by stefaniebutland** [comment]
@IleanaF please review these additions in the website draft pull request [preview](https://deploy-preview-63--pathways-to-open-science-preview.netlify.app/) [source](https://github.com/Openscapes/pathways-to-open-science/pull/63) when you have time. Ideally we could do it in a short screenshare so you can practice using GitHub.com tools for that, but you are also very welcome to add feedback in a comment on the pull request.

- [ ] Could it say "This is an ongoing Openscapes collaboration with Black in Marine Science..."? since Openscapes' role not clear till much lower on page. This is the text I used.
- [ ] LaWanda's bio
- [ ] Funding text
- [ ] all dates
- [ ] Alex's bio

Stef TODO

- [ ] update bims-bweems-openscapes logo bottom of Home
- [ ] add HBCU logos (Ileana, which of your presentations is best for these?)
- [ ] make a new Release on GitHub for site including 2024 content
- [ ] update citation instructions when new Release is done

**Comment by IleanaF** [comment]
@stefaniebutland it looks amazing! That is ready to go. I like the updated Openscapes terminology.

**Comment by stefaniebutland** [comment]
Thanks for reviewing it Ileana! Updated site is now live.

@aneesewilliams & @alexcddavis would you please review your bios on the [Pathways site](https://openscapes.github.io/pathways-to-open-science/#planning-team) and comment here with an ok, or request for updates?

**Comment by aneesewilliams** [comment]
Updates:
1. I am also on the Science Core Heuristics for Open Science Outcomes in Learning (SCHOOL) Open Science Team (OST) with Columbia Climate School.
2. NSF BIO-LEAPS Advisory Board Member

**Comment by stefaniebutland** [comment]
Thanks @aneesewilliams ! Your [updated bio](https://openscapes.github.io/pathways-to-open-science/#planning-team) is live now

**Comment by stefaniebutland** [comment]
@IleanaF Would you like me to add HBCU logos at the bottom of the home page? Where should I look for the logos?

**Comment by IleanaF** [comment]
@stefaniebutland I have them all at the end of [this PPT](https://docs.google.com/presentation/d/10OxU37xNfkRmyUA5srQvdxglwbNFSa11RCMQ3MaDJTU/edit?usp=sharing) as PNGs, would this work?

**Comment by stefaniebutland** [comment]
That works thanks!

**Comment by stefaniebutland** [comment]
Hi @Lawandaw! I've created a short bio for you on the [Pathways website](https://openscapes.github.io/pathways-to-open-science/#planning-team). Can you please check it and reply here with any edits you'd like me to make?

**Comment by lawandaw** [comment]
> Hi @lawandaw! I've created a short bio for you on the [Pathways website](https://openscapes.github.io/pathways-to-open-science/#planning-team). Can you please check it and reply here with any edits you'd like me to make?

Hi @stefaniebutland :) I have viewed the bio and it is fine with me. Thanks!

**Comment by stefaniebutland** [comment]
@IleanaF Added [HBCU logos](https://openscapes.github.io/pathways-to-open-science/#our-hbcu-partners). Realizing it could go above Citation, but not critical. Happy to make any edits.

**Comment by IleanaF** [comment]
Wow, thats so cool to see on the website. A real visual of the impact moment for me. Thank you for updating that Stef. It looks great and agreed, not critical. Let's leave it like this right now. 

@stefaniebutland

**Comment by stefaniebutland** [comment]
@IleanaF I don't plan to make a new GitHub release or update the citation now. Can do that when we make Certificates for 2025. Looks like this issue is 👍🏼 to close.

**Comment by IleanaF** [comment]
Woohooo!!! Closing with this comment. Thank you @stefaniebutland
