### ISSUE TITLE
Save the Date Flyer & One Page PDF 

### ISSUE THREAD

**Issue by IleanaF** [Openscapes/pathways-to-open-science#51]
### Deadline:  **December 5th** 

- [x] Save the date flyer for feedback 
- [x] Updated 1 pager for program this year 

Prior to December 5th: 
- [x] sample deck of "updates" to branding for approval -> please share before any major changes to current flyers 

### Notes for Updating Content 
**All Content**
- Dates for this year are: Thursdays: Jan 23, 30; Feb 6, 13, 20, 27 from 5-6:30 PM EST (note all events are now 5-6:30 EST vs. 5-6 PM for coworking last year) 
- PreReview is not a partner this year and can be removed from this year's content 
- Please add Openscapes on Bluesky [@openscapes.bsky.social] (https://bsky.app/profile/openscapes.bsky.social) 
- I am currently really iffy about Twitter and whether we will be posting there at all...we'll decide in our team meeting on Dec. 2nd and let you know ASAP. For rn plan to replace Twitter's logo and whatnot with Bluesky and I'll ask the other orgs if they have Bluesky or another platform to share. 
- registration (via zoom) will open with the post of the save the date flyer and sharing of one pager -> I realize we have the QR code and I'll talk to Stef tomorrow about opening registration so we can have that on the flyer

**Save the date flyer**
>  ![Image](https://github.com/user-attachments/assets/a143ce38-9536-473c-8fee-2e86805e5589)

**Notes from Team** 
- really liked [flyer](https://drive.google.com/file/d/15dVvtvg8Nox0Z1ahUYHs5FPmwJpfCveL/view?usp=sharing) from last year! We brainstormed some possible phrasing to include if it aligned: "the journey continues!" 
-  I am going to start it in the comment below but we were thinking of using this phrasing to start the caption and welcome people to register...“We are a community of Black marine scientists creating a...” Join us and help us grow our community 
- Maybe a "Starts on January 23rd!" mention on flyer if you feel like that fits somewhere well 
- I copied over relevant comments but [here](https://docs.google.com/document/d/1QaHEXUf9UAp5c4nrHaDwtWyvwIVQEjtexx5UtHS2OTg/edit?tab=t.0#bookmark=id.5deai54cthgu) is where we are in seaside chats document for reference  

**One Pager**
[One Pager](https://drive.google.com/file/d/18vthdktDoRUgcM6T_m9jYDP5it8SzOIX/view?usp=sharing)
 - still love one pager! 
 - please refer to all content updates above -- [Here is an issue](https://github.com/Openscapes/pathways-to-open-science/issues/60) with those notes for easier reference back. 

Questions for LaWanda 
- What date will you have an updated content calendar and be ready to share with orgs? 
- When should we blast the save the date content in your opinion? Goal: get it on people's radar before heading into new year 
- What is the best way to share small wording changes (RE: one pager)? Right now I think it is good but I am going to review. When would be best for you to get it by? Give me a date.

**Comment by lawandaw** [comment]
Hi everyone! So sorry for the delay but I am super excited to be working with everyone again. 

I wanted to attach the "Save the Date" flyers here and give you all access to the public [canva link](https://www.canva.com/design/DAGYhrteDD0/MHxChGy2jqQpKYrx6sZfag/edit?utm_content=DAGYhrteDD0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) so you can see the progress in content creation. You all can comment on content drafts here and directly on the canva link! The drafts are pretty complete except for the bluesky or twitter alternate handles. I have a MP4 and a PNG file for both flyers. 

https://github.com/user-attachments/assets/33aa305d-277a-4c50-afb8-2fe7ceffde16

![December Graphic 1-1](https://github.com/user-attachments/assets/605cfc9e-2303-4f7b-b5a3-e7657dcc189d)

https://github.com/user-attachments/assets/390d26d3-5b17-4298-b8b8-e6970f0659ff

![December Graphic 1-2](https://github.com/user-attachments/assets/6ae4700a-374b-4177-bc42-04db353aa91f)

@IleanaF I wanted to still answer these questions as well: 
> Questions for LaWanda
> 
> * What date will you have an updated content calendar and be ready to share with orgs? **_I would like to have the content calendar finalized and shared with the other organizations by Jan 10th. Hopefully, I will have a final draft for you all to see by the 23rd of this month._** 
> * When should we blast the save the date content in your opinion? Goal: get it on people's radar before heading into new year **_I think the Save the Date flyer could be posted on the 27th._** 
> * What is the best way to share small wording changes (RE: one pager)? Right now I think it is good but I am going to review. When would be best for you to get it by? Give me a date. **_You can text or email them to me! If you want to leave them here and mention me, that is fine as well._** 

Also wanted to share the QR code for that is attached to this as well! 
![Registration QR](https://github.com/user-attachments/assets/f1ee17ff-cbe6-4e14-9068-d76ea24e4c82)

**Comment by IleanaF** [comment]
- [ ] Connect @lawandaw to Rose from BWEEMS via email for this year

**Comment by IleanaF** [comment]
Hey @lawandaw !

Thank you for these drafts. Our team feedback is [here](https://docs.google.com/document/d/1QaHEXUf9UAp5c4nrHaDwtWyvwIVQEjtexx5UtHS2OTg/edit?tab=t.0#bookmark=id.c2cu28uty9ir), please paste your drafts as a comment here and @ me to review ASAP so I can give any final comments for approval before you leave for your holiday!

**Comment by lawandaw** [comment]
Hi everyone! Thank you for the feedback, I have applied it all and the new drafts are listed below. @IleanaF 
[Pathways to Open Science.pdf](https://github.com/user-attachments/files/18097539/Pathways.to.Open.Science.pdf)

https://github.com/user-attachments/assets/f3aa3986-8d60-43e9-9a16-a4d89cc36344

https://github.com/user-attachments/assets/921087d2-0e8d-44ec-b7da-f5c7a9c94871

**Comment by IleanaF** [comment]
Awesome, thank you LaWanda! 

**One pager**
Comments for revision (from top to bottom) 
- I think we'd like to see a version with only one font throughout the entire one pager
- "This 6 part remote event series runs on Thursdays..." this section the spacing between the first and second line seems tighter than throughout the rest of the flyer & there is no space on the side with 5:00 PM- 6:30 PM EST -> 5:00 PM - 6:30 PM
- Feb 20th section, the text jumps down in the latter part of the description. Also it looks like science in that sentence hangs off a bit further then "will" at the end of the line in the January 23rd section. Similarly with the coworking description, can they all be aligned to cut off at the same point? 
- Hear our speakers stories part - need a comma after develop new data science skills, and more! 

Save the date flyer part 1 looks good to me. 
Save the date flyer part 2 
- Cut "Join our growing community" -> can we move this into the caption? 
- I'm gonna tag the team via Slack to see if they have additional thoughts for you today 

@lawandaw

**Comment by lawandaw** [comment]
Hello again! Here are the update versions with those edits. 
[Pathways to Open Science (1).pdf](https://github.com/user-attachments/files/18111948/Pathways.to.Open.Science.1.pdf)

https://github.com/user-attachments/assets/fa574757-8e97-4620-9f94-5731e4a5520b


https://github.com/user-attachments/assets/2eacd0e6-fb5b-4d59-a130-7dd26608799a

**Comment by IleanaF** [comment]
Looks good! I am asking the team slack is someone else can give it a second glance for final approval but I have no further edits. Will confirm by 5 PM EST. 

Once complete, can we name the PDF one pager "2025_PathwaystoOpenScience_OnePager" for the final version? 

@lawandaw

**Comment by IleanaF** [comment]
I also wanted to add a note reviewing the task list items from the earlier posts in this issue  (RE:  sample deck of "updates" to branding for approval) -> do you have any major branding components that are shifting? please share for approval before implementation. If not, we can mark this for a later development conversation.

**Comment by stefaniebutland** [comment]
Hi @lawandaw @IleanaF. The updated flyer looks great; nice and "clean". A couple of notes:

- [ ] the punctuation for "3 community calls ..."and "3 coworking sessions ..."  is different. Use same structure. Suggestion:
  - 3 community calls - 1.5 hour meetings with facilitated discussion, mini-lectures and community conversations:
  - 3 coworking sessions - 1.5 hour calls structured for you to bring your
own work, practice skill building, screenshare, and ask questions: 
- [ ]  The X logo doesn't show clearly 
- [ ] Make exclamation same colour as text in "No coding experience is required!"
- [ ] "learn efficiency tricks" ->  learn efficiency tips

**Comment by IleanaF** [comment]
Thank you for taking a look @stefaniebutland !!

**Comment by aneesewilliams** [comment]
Hello @lawandaw & @IleanaF  I love the Updated Save the Date Graphics 👍 Can't wait to post them!!

For the One Page Flyer - Maybe it's just me but at the top "Hosted by Openscapes, Black in Marine Science, and Black Women in Ecology, Evolution, and Marine Science" becomes harder to read as the waves/water color changes from dark to light. Could a solid background behind the text be added? Possibly the same color used at the bottom where it has all the connect with us information?

**Comment by lawandaw** [comment]
Thank you everyone for your feedback! I have implemented them all in both of these drafts. They are also uploaded to the Google Drive as well. Please let me know if you want to make any more changes :)
[Uploading Pathways to Open Science One-Pager.pdf…]()

**Comment by IleanaF** [comment]
Sending off content emails now and closing this issue, thank you @lawandaw for this first push for promo!!
