### ISSUE TITLE
Team Lead Post Meeting 1 Tasks

### ISSUE THREAD

**Issue by IleanaF** [Openscapes/pathways-to-open-science#57]
- [x] Draft and send email to NOAA contacts for invite to coworking and referrals for NOAA speakers
- [x] Share feedback for "Save the Date" flyer with LaWanda 
- [x] Slack messages issue for leading up to new year engagement 
- [x] @jules32  add Aneese and Alex to calendar invitations

**Comment by IleanaF** [comment]
@jules32 Can you add Alex, Aneese and Stef as well if she's not already on to our Calendar holds for 2025? Thank you!

**Comment by jules32** [comment]
Done! We'll update the Zoom call in information when we have it, but it's a placeholder for our team's calendars now.

**Comment by IleanaF** [comment]
- [ ] send out Calendly for next meeting
