### ISSUE TITLE
Pathways to Open Science Team Connects on Github! 

### ISSUE THREAD

**Issue by IleanaF** [Openscapes/pathways-to-open-science#58]
Woohoo! Respond with a comment or emoji when you've followed everyone on the team on Github and checked out this issue 🥇 

@stefaniebutland & @jules32 When I go to assign this issue, I see that Aneese and Alex are not an option, can I only assign to folks within the organization? Can we give Alex and Aneese admin access to our project and repository for Pathways? (not sure how this is nestled within the Openscapes broader umbrella so let me know what works with the current structure).

**Comment by jules32** [comment]
@IleanaF I've added @alexcddavis and @aneesewilliams  as maintainers to this repository!

**Comment by IleanaF** [comment]
Thanks Julie! 

@alexcddavis & @aneesewilliams Respond with a comment or emoji when you've followed everyone on the team on Github and checked out this issue 🥇

**Comment by aneesewilliams** [comment]
Done!

**Comment by alexcddavis** [comment]
🙌
