### ISSUE TITLE
Create Zoom registration

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/pathways-to-open-science#61]
Adapt from 2024 version. When completed, add to website 

[how-to](https://openscapes.github.io/approach-guide/approach/tooling.html#zoom) in Approach Guide

**Comment by stefaniebutland** [comment]
Thanking past Me for creating a Zoom Template for Pathways
![Screenshot 2024-11-26 at 11 18 03 AM](https://github.com/user-attachments/assets/a729c630-cf02-4bce-936b-8003960434d2)

**Comment by stefaniebutland** [comment]
Wondering if "Close registration after meeting date" should *not* be selected; but changing is not an option. Must have been what we used in 2024

![Screenshot 2024-11-26 at 11 31 48 AM](https://github.com/user-attachments/assets/663efdb3-2e70-4b10-8bfc-0544568448a4)

**Comment by IleanaF** [comment]
@stefaniebutland This looks great! Do you think it means after the final event of the series or after the first event's completion? I'd like for folks to be able to still register and join us after the first event if thats possible.

**Comment by jules32** [comment]
This might be a tangent but I thought this was a very cool way to use Zoom registration for a whole conference program: https://events.zoom.us/ev/Asg4hCYlKUnIia-OW9lpF8c8ne9P66sjzrLdMbvkXGguK3Z9ih_C~AkQ62ZVQEjbIM4hWpTU4BE37MveEIDNQKPFqeMZsg8Dm93CJvYqQhFKDUg?lmt=1726533984000

**Comment by stefaniebutland** [comment]
@IleanaF I think this registration will do what we want - allow ongoing registration till after the final call.
Here's a very [cryptic answer](https://community.zoom.com/t5/Zoom-Meetings/Close-registration-after-the-meeting-date-Recurring-Meetings/m-p/27222/highlight/true#M13360) from Zoom help

Let's plan to test registration on Jan 24!

**Comment by stefaniebutland** [comment]
cool re: Zoom for full event @jules32. And clicking on a talk leads to the recording!

**Comment by stefaniebutland** [comment]
@IleanaF Please register via [zoom](https://zoom.us/meeting/register/tJ0vc-2grzgrH9URmxCRyV34ZwjvcwCU0ciH) and request any updates to the registration page and to the registration confirmation email you receive.

**Comment by IleanaF** [comment]
Registered and it looks great, thank you @stefaniebutland !

**Comment by stefaniebutland** [comment]
done
