### ISSUE TITLE
Past Participant Speaker Coordination

### ISSUE THREAD

**Issue by IleanaF** [Openscapes/pathways-to-open-science#72]
- [x] ID past participant speaker invitations 
- [x] Email draft to past participant speakers
- [x] Email sent 

Note to do later -> Sent personal invite to folks who spoke last year (Aliyah and Barbara)

**Comment by IleanaF** [comment]
Previous content of email from Alex: 

Hi Barbara and Happy new year!
On behalf of the Pathways team I am excited to extend an offer to increase your involvement in this year's Pathways to Open Science 6-week series.
Because you participated in it last year we would like to invite you to share your story of how Pathways helped you.
The commitment is low. We ask that during our first or second community call that you spend 3-5 minutes talking about your experience with the Pathways program. This can be as simple as mentioning a new resource you heard about! We will have a few guiding questions to help. We feel that stories are so important for those just beginning their journey, and we would love for you to share yours.

If you have any questions feel free to reach out to me or Ileana (ccd here) .  
Can you please let us know if you are interested and if so, which date or dates work well for you? 
The dates are: January 25 or February 8th.

Looking forward to hearing from you!

Alex and the Pathways Team

And here is a [link ](https://openscapes.github.io/pathways-to-open-science/)to our updated website.

**Comment by aneesewilliams** [comment]
Made edits to the draft email, I am prepared to send emails on Monday 👍

**Comment by aneesewilliams** [comment]
Sent emails!

**Comment by IleanaF** [comment]
thank you @aneesewilliams closing this issue!!
